[project]
authors = ["narenp12 <narenprax@ucla.edu>"]
channels = ["conda-forge"]
name = "stats140finalproj"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.3,<3"
statsmodels = ">=0.14.4,<0.15"
plotly = ">=6.0.0,<7"
matplotlib = ">=3.10.1,<4"
scikit-learn = ">=1.6.1,<2"
ipykernel = ">=6.29.5,<7"
jupyter = ">=1.1.1,<2"
seaborn = ">=0.13.2,<0.14"
pyarrow = ">=19.0.1,<20"
fastparquet = ">=2024.11.0,<2025"
lightgbm = ">=4.6.0,<5"
quarto = ">=1.6.42,<2"

[pypi-dependencies]
skforecast = ">=0.13.0, <0.14"
